---
services:
  db:
    container_name: postgres-dev
    image: postgres
    restart: unless-stopped
    volumes:
      - ./dev/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=illegitimate
