version: '3.7'
services:
  illegitimate:
    container_name: illegitimate
    build:
      context: .
      dockerfile: Dockerfile
    image: illegitimate:latest
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
      - ${DB_PATH}:/app/data
    environment:
      - TOKEN=${TOKEN}
      - MONGOURI=${MONGOURI}
      - DEV=${DEV}
      - HYPIXELAPIKEY=${HYPIXELAPIKEY}
      - REDISURI=${REDISURI}
