---
services:
  illegitimate:
    container_name: illegitimate
    image: registry.gitlab.com/illegitimate/illegitimate-bot:main
    restart: unless-stopped
    logging:
      driver: journald
    environment:
      - TOKEN=${TOKEN}
      - MONGOURI=${MONGOURI}
      - DEV=${DEV}
      - HYPIXELAPIKEY=${HYPIXELAPIKEY}
      - REDISURI=${REDISURI}
      - POSTGRESURI=${POSTGRESURI}
    depends_on: 
      - db
    pull_policy: always
  db:
    container_name: illegitimate-postgres
    image: postgres
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=illegitimate
