version: '3.7'
services:
  illegitimate:
    container_name: illegitimate
    build:
      context: .
      dockerfile: Dockerfile
    image: illegitimate:latest
    restart: unless-stopped
    logging:
      driver: journald
    environment:
      - TOKEN=${TOKEN}
      - MONGOURI=${MONGOURI}
      - DEV=${DEV}
      - HYPIXELAPIKEY=${HYPIXELAPIKEY}
      - REDISURI=${REDISURI}
      - POSTGRESURI=${POSTGRESURI}
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
      - ${DB_PATH}:/app/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=illegitimate
